name: titles_example
description: Example App for 'titles' package

version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  faker: 1.2.1
  editors: ^0.0.9
  titles:
    path: ../

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
